### ISSUE TITLE
Not a Issue ---- Multiple SDRs

### ISSUE THREAD

**Issue by Stormtracker017** [lheijst/weewx-rtldavis#2]
I have two SDR's running on the RPI:

0:  Realtek, RTL2838UHIDIR, SN: 0433
1:  Realtek, RTL2838UHIDIR, SN: 0915

Is their a way to tell RTLDavis to use 1:0915?

**Comment by lheijst** [comment]
Not tested:
Change in main.go line:
    dev, err := rtlsdr.Open(0)
into:
    dev, err := rtlsdr.Open(1)

Hope this helps.

Luc

**Comment by Stormtracker017** [comment]
It works.  This driver been running for over 38 days with out any issues. 
Thanks Luc
