### ISSUE TITLE
Not a Issue ---  Saving Frequency Errors US to database

### ISSUE THREAD

**Issue by Stormtracker017** [lheijst/weewx-rtldavis#3]
Luc

How can I modify this code to save the errors to the weewx database?

if self.frequency == 'EU':
                pkt['dateTime'] = int(time.time() + 0.5)
                pkt['usUnits'] = weewx.METRIC
                for y in range(0, 5):
                    if int(m.group(1)) == y:
                        pkt['freqError%d' % y] = int(m.group(3))
                dbg_rtld(3, "chan_pkt: %s" % pkt)
 else:
    dbg_rtld(3, "Don't store freqErrors for frequency band %s" % self.frequency)
     lines.pop(0)
     return pkt

Thanks
Rich

**Comment by lheijst** [comment]
Rich,

if self.frequency == ‘US’

is one way to get it done. Only the errors of the first five frequencies are stored.

Luc

Verstuurd vanaf mijn iPad

**Comment by Stormtracker017** [comment]
Thanks Luc
It works with a visual display.
Rich
![SDR Freq error](https://user-images.githubusercontent.com/48191231/59161131-8c0a3d00-8aac-11e9-9456-ae6639d6406f.png)
