### ISSUE TITLE
Fresh install does not pull rtldavis in ~/work/ folder

### ISSUE THREAD

**Issue by HRmeteohub** [lheijst/weewx-rtldavis#4]
Hello!
First, thank you for very nice tool for capturing the measurements from Davis weather stations. It hits the need right on, much better than ancient tech - that Davis consoles are.
However, this morning I just did a fresh install of weewx-rtldavis on raspberry pi 4 with Raspibian/Python3. It failed in step 7:
`pi@raspberrypi:~ $ sudo PYTHONPATH=bin python bin/user/rtldavis.py --cmd="/home/pi/work/bin/rtldavis"
python: can't open file 'bin/user/rtldavis.py': [Errno 2] No such file or directory
`
So, I have looked at the procedure and found out that there is no step where rtldavis is installed. Therefore the ~/work/ folder is empty. Or did I made an error in my ways?

Thank you.
Tom

**Comment by lheijst** [comment]
Hi Tom,
Have a look at https://github.com/lheijst/rtldavis.
Here is described the installation of rtldavis which is used by weewx-rtldavis.
Success,
Luc

Verstuurd vanaf mijn iPad

**Comment by HRmeteohub** [comment]
Hello.

After a considerable testing and combing through internet, I finally realized that my problems with weewx-rtldavis happened because not all USB SDR receivers are the same.  There are many, many that are ... bad.
