### ISSUE TITLE
Python 3 Log Open Fails

### ISSUE THREAD

**Issue by gary-hammer** [lheijst/weewx-rtldavis#5]
Weewx 4.1.1 running on Pop!OS 20.04 with Python 3.8.5, setup.py method so /home/weewx

I have installed the prereqs for this driver and have been able to run rtldavis from the command line on my server.
`$GOPATH/bin/rtldavis -tr 3 -tf US -ppm 78 `

I then installed into weewx.

To test, I use
`PYTHONPATH=bin python3 bin/user/rtldavis.py --cmd="/home/weewx/bin/rtldavis"`

I get the error shown in the attached file 'error1.txt'

Running weewxd produces loop, archive and creates webpages. The problem that I needed to run directly for is that my barometer shows N/A in weewx. Without running directly I am not able to troubleshoot this.

[error1.txt](https://github.com/lheijst/weewx-rtldavis/files/5393213/error1.txt)

**Comment by lheijst** [comment]
Logging fixed in version 0.19
