### ISSUE TITLE
Pressure Not Seen/Recorded

### ISSUE THREAD

**Issue by gary-hammer** [lheijst/weewx-rtldavis#6]
Running weewx 4.1.1, Python 3.8, setup.py install on Pop!OS 20.04

I have installed the prereqs and find that I get data from my 2 transmitters ISS and Wind.
I am not seeing any barometer data in WeeWX though.
My console has barometer readings, so I believe the data is transmitted.

I did enable logging, log_unknown_sensors = True log_unmapped_sensors = True in weewx.conf
With weewx debug logging on, I captured logs for a period of time. Attaching file 'nopressure.txt' 
Line 15 has the first unknown packet logged. There are others as well.

Any ideas?
[nopressure.txt](https://github.com/lheijst/weewx-rtldavis/files/5393603/nopressure.txt)

**Comment by lheijst** [comment]
The ISS and Anemometer don’t have a barometer sensor. This sensor is build in the Davis console which data is not available in this driver. You will have to use a separate pressure device like the BMP280 which can be read by a weewx service.

**Comment by gary-hammer** [comment]
Oops, RTFM.

Thanks for the idea on getting pressure into WeeWX.
